
# Dockerfile to build compiler tools (may require large base images)
FROM ubuntu:22.04
RUN apt-get update && apt-get install -y build-essential cmake
COPY . /src
WORKDIR /src
RUN mkdir -p build && cd build && cmake .. && make
