
name: Build and Test (sim mode)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
          pip install pytest flake8
      - name: Run pytest
        run: pytest tests/python_tests -q
      - name: Run demo (sim)
        run: |
          python python/src/cli.py
          python python/src/bench/run_bench.py --sim
      #- name: Build C++ stub
        # run: |
        #   mkdir -p compiler/build && cd compiler/build && cmake .. && make || true
